"""fix

Revision ID: 40c59e016f10
Revises: ab1aada4a119
Create Date: 2026-09-25 20:16:52.046416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c59e016f10'
down_revision: Union[str, Sequence[str], None] = 'ab1aada4a119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'justification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('justification', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
