"""like unique user post

Revision ID: 8cd61c621d12
Revises: a0365ba03323
Create Date: 2026-09-28 22:13:58.060871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd61c621d12'
down_revision: Union[str, Sequence[str], None] = 'a0365ba03323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_likes_user_post', 'likes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_likes_user_post', 'likes', type_='unique')
    # ### end Alembic commands ###
