"""like count added in post

Revision ID: b7200e138dcd
Revises: 8cd61c621d12
Create Date: 2026-10-01 23:08:58.252279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7200e138dcd'
down_revision: Union[str, Sequence[str], None] = '8cd61c621d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE posts SET likes_count = 0 WHERE likes_count IS NULL")
    op.alter_column('posts', 'likes_count', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes_count')
    # ### end Alembic commands ###
